export const categories = [
  { id: 'news', name: 'News', icon: 'Newspaper' },
  { id: 'sports', name: 'Sports', icon: 'Trophy' },
  { id: 'movies', name: 'Movies', icon: 'Film' },
  { id: 'entertainment', name: 'Entertainment', icon: 'Sparkles' },
  { id: 'kids', name: 'Kids', icon: 'Baby' },
  { id: 'music', name: 'Music', icon: 'Music' },
  { id: 'documentary', name: 'Documentary', icon: 'BookOpen' },
  { id: 'religious', name: 'Religious', icon: 'Church' },
  { id: 'bangla', name: 'Bangla Channels', icon: 'Globe' },
  { id: 'international', name: 'International', icon: 'Earth' },
  { id: 'hd', name: 'HD Channels', icon: 'MonitorPlay' },
  { id: 'live', name: 'Live Events', icon: 'Radio' },
];

const DEMO_HLS_URL = 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8';
const DEAD_HLS_URL = 'https://example.invalid/stream.m3u8';

const gradientMap = {
  'from-red-500 to-red-700': 'linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)',
  'from-blue-600 to-blue-800': 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
  'from-orange-500 to-orange-700': 'linear-gradient(135deg, #f97316 0%, #c2410c 100%)',
  'from-cyan-500 to-cyan-700': 'linear-gradient(135deg, #06b6d4 0%, #0e7490 100%)',
  'from-indigo-600 to-indigo-800': 'linear-gradient(135deg, #4f46e5 0%, #3730a3 100%)',
  'from-blue-500 to-blue-700': 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
  'from-red-600 to-red-800': 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
  'from-yellow-500 to-yellow-700': 'linear-gradient(135deg, #eab308 0%, #a16207 100%)',
  'from-purple-600 to-purple-800': 'linear-gradient(135deg, #9333ea 0%, #6b21a8 100%)',
  'from-green-500 to-green-700': 'linear-gradient(135deg, #22c55e 0%, #15803d 100%)',
  'from-purple-700 to-purple-900': 'linear-gradient(135deg, #7e22ce 0%, #581c87 100%)',
  'from-pink-600 to-pink-800': 'linear-gradient(135deg, #db2777 0%, #9d174d 100%)',
  'from-teal-500 to-teal-700': 'linear-gradient(135deg, #14b8a6 0%, #0f766e 100%)',
  'from-amber-600 to-amber-800': 'linear-gradient(135deg, #d97706 0%, #92400e 100%)',
  'from-rose-600 to-rose-800': 'linear-gradient(135deg, #e11d48 0%, #9f1239 100%)',
  'from-violet-600 to-violet-800': 'linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)',
  'from-yellow-600 to-yellow-800': 'linear-gradient(135deg, #ca8a04 0%, #854d0e 100%)',
  'from-pink-500 to-pink-700': 'linear-gradient(135deg, #ec4899 0%, #be185d 100%)',
  'from-purple-500 to-purple-700': 'linear-gradient(135deg, #a855f7 0%, #7e22ce 100%)',
  'from-orange-600 to-orange-800': 'linear-gradient(135deg, #ea580c 0%, #9a3412 100%)',
  'from-blue-500 to-purple-600': 'linear-gradient(135deg, #3b82f6 0%, #9333ea 100%)',
  'from-blue-400 to-blue-600': 'linear-gradient(135deg, #60a5fa 0%, #2563eb 100%)',
  'from-emerald-600 to-emerald-800': 'linear-gradient(135deg, #059669 0%, #065f46 100%)',
  'from-teal-600 to-teal-800': 'linear-gradient(135deg, #0d9488 0%, #115e59 100%)',
  'from-gray-600 to-gray-800': 'linear-gradient(135deg, #4b5563 0%, #1f2937 100%)',
  'from-red-700 to-red-900': 'linear-gradient(135deg, #b91c1c 0%, #7f1d1d 100%)',
};

const baseChannels = [
  { id: 'news-1', name: 'CNN International', category: 'news', logo: 'C', gradient: 'from-red-500 to-red-700', isLive: true },
  { id: 'news-2', name: 'BBC World News', category: 'news', logo: 'B', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'news-3', name: 'Al Jazeera English', category: 'news', logo: 'A', gradient: 'from-orange-500 to-orange-700', isLive: true },
  { id: 'news-4', name: 'Sky News', category: 'news', logo: 'S', gradient: 'from-cyan-500 to-cyan-700', isLive: true },
  { id: 'news-5', name: 'Fox News', category: 'news', logo: 'F', gradient: 'from-indigo-600 to-indigo-800', isLive: true },
  { id: 'news-6', name: 'CNBC', category: 'news', logo: 'C', gradient: 'from-blue-500 to-blue-700', isLive: true },
  { id: 'sports-1', name: 'ESPN', category: 'sports', logo: 'E', gradient: 'from-red-600 to-red-800', isLive: true },
  { id: 'sports-2', name: 'Star Sports 1', category: 'sports', logo: 'S', gradient: 'from-yellow-500 to-yellow-700', isLive: true },
  { id: 'sports-3', name: 'Sky Sports', category: 'sports', logo: 'S', gradient: 'from-blue-500 to-blue-700', isLive: false },
  { id: 'sports-4', name: 'beIN Sports', category: 'sports', logo: 'B', gradient: 'from-purple-600 to-purple-800', isLive: true },
  { id: 'sports-5', name: 'Eurosport', category: 'sports', logo: 'E', gradient: 'from-green-500 to-green-700', isLive: true },
  { id: 'sports-6', name: 'TSN', category: 'sports', logo: 'T', gradient: 'from-red-500 to-red-700', isLive: false },
  { id: 'movies-1', name: 'HBO', category: 'movies', logo: 'H', gradient: 'from-purple-700 to-purple-900', isLive: true },
  { id: 'movies-2', name: 'Star Movies', category: 'movies', logo: 'S', gradient: 'from-pink-600 to-pink-800', isLive: true },
  { id: 'movies-3', name: 'Sony Pix', category: 'movies', logo: 'S', gradient: 'from-teal-500 to-teal-700', isLive: true },
  { id: 'movies-4', name: 'Cinemax', category: 'movies', logo: 'C', gradient: 'from-amber-600 to-amber-800', isLive: false },
  { id: 'movies-5', name: 'AXN', category: 'movies', logo: 'A', gradient: 'from-rose-600 to-rose-800', isLive: true },
  { id: 'movies-6', name: 'Warner TV', category: 'movies', logo: 'W', gradient: 'from-violet-600 to-violet-800', isLive: true },
  { id: 'ent-1', name: 'Comedy Central', category: 'entertainment', logo: 'C', gradient: 'from-yellow-600 to-yellow-800', isLive: true },
  { id: 'ent-2', name: 'E! Entertainment', category: 'entertainment', logo: 'E', gradient: 'from-pink-500 to-pink-700', isLive: true },
  { id: 'ent-3', name: 'TLC', category: 'entertainment', logo: 'T', gradient: 'from-purple-500 to-purple-700', isLive: false },
  { id: 'ent-4', name: 'Star World', category: 'entertainment', logo: 'S', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'ent-5', name: 'Colors TV', category: 'entertainment', logo: 'C', gradient: 'from-red-600 to-red-800', isLive: true },
  { id: 'ent-6', name: 'Zee TV', category: 'entertainment', logo: 'Z', gradient: 'from-orange-600 to-orange-800', isLive: true },
  { id: 'kids-1', name: 'Disney Channel', category: 'kids', logo: 'D', gradient: 'from-blue-500 to-purple-600', isLive: true },
  { id: 'kids-2', name: 'Cartoon Network', category: 'kids', logo: 'C', gradient: 'from-cyan-500 to-cyan-700', isLive: true },
  { id: 'kids-3', name: 'Nickelodeon', category: 'kids', logo: 'N', gradient: 'from-orange-500 to-orange-700', isLive: true },
  { id: 'kids-4', name: 'Pogo', category: 'kids', logo: 'P', gradient: 'from-green-500 to-green-700', isLive: false },
  { id: 'kids-5', name: 'Nick Jr', category: 'kids', logo: 'N', gradient: 'from-pink-500 to-pink-700', isLive: true },
  { id: 'kids-6', name: 'Baby TV', category: 'kids', logo: 'B', gradient: 'from-blue-400 to-blue-600', isLive: true },
  { id: 'music-1', name: 'MTV', category: 'music', logo: 'M', gradient: 'from-pink-600 to-pink-800', isLive: true },
  { id: 'music-2', name: 'VH1', category: 'music', logo: 'V', gradient: 'from-purple-600 to-purple-800', isLive: true },
  { id: 'music-3', name: '9XM', category: 'music', logo: '9', gradient: 'from-red-500 to-red-700', isLive: true },
  { id: 'music-4', name: 'MTV Hits', category: 'music', logo: 'M', gradient: 'from-blue-600 to-blue-800', isLive: false },
  { id: 'music-5', name: 'Zing', category: 'music', logo: 'Z', gradient: 'from-yellow-500 to-yellow-700', isLive: true },
  { id: 'music-6', name: 'B4U Music', category: 'music', logo: 'B', gradient: 'from-teal-500 to-teal-700', isLive: true },
  { id: 'doc-1', name: 'National Geographic', category: 'documentary', logo: 'N', gradient: 'from-yellow-500 to-yellow-700', isLive: true },
  { id: 'doc-2', name: 'Discovery Channel', category: 'documentary', logo: 'D', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'doc-3', name: 'History TV', category: 'documentary', logo: 'H', gradient: 'from-amber-600 to-amber-800', isLive: true },
  { id: 'doc-4', name: 'Animal Planet', category: 'documentary', logo: 'A', gradient: 'from-green-600 to-green-800', isLive: true },
  { id: 'doc-5', name: 'TLC HD', category: 'documentary', logo: 'T', gradient: 'from-purple-600 to-purple-800', isLive: false },
  { id: 'doc-6', name: 'BBC Earth', category: 'documentary', logo: 'B', gradient: 'from-emerald-600 to-emerald-800', isLive: true },
  { id: 'rel-1', name: 'Peace TV', category: 'religious', logo: 'P', gradient: 'from-green-600 to-green-800', isLive: true },
  { id: 'rel-2', name: 'Aastha', category: 'religious', logo: 'A', gradient: 'from-orange-600 to-orange-800', isLive: true },
  { id: 'rel-3', name: 'God TV', category: 'religious', logo: 'G', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'rel-4', name: 'Sanskar TV', category: 'religious', logo: 'S', gradient: 'from-purple-600 to-purple-800', isLive: true },
  { id: 'rel-5', name: 'Paigam TV', category: 'religious', logo: 'P', gradient: 'from-teal-600 to-teal-800', isLive: false },
  { id: 'rel-6', name: 'Divya TV', category: 'religious', logo: 'D', gradient: 'from-rose-600 to-rose-800', isLive: true },
  { id: 'bangla-1', name: 'Star Jalsha', category: 'bangla', logo: 'S', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'bangla-2', name: 'Zee Bangla', category: 'bangla', logo: 'Z', gradient: 'from-purple-600 to-purple-800', isLive: true },
  { id: 'bangla-3', name: 'Colors Bangla', category: 'bangla', logo: 'C', gradient: 'from-red-600 to-red-800', isLive: true },
  { id: 'bangla-4', name: 'Sony Aath', category: 'bangla', logo: 'S', gradient: 'from-green-600 to-green-800', isLive: true },
  { id: 'bangla-5', name: 'Jalsha Movies', category: 'bangla', logo: 'J', gradient: 'from-pink-600 to-pink-800', isLive: false },
  { id: 'bangla-6', name: 'ATN Bangla', category: 'bangla', logo: 'A', gradient: 'from-teal-600 to-teal-800', isLive: true },
  { id: 'int-1', name: 'France 24', category: 'international', logo: 'F', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'int-2', name: 'DW News', category: 'international', logo: 'D', gradient: 'from-gray-600 to-gray-800', isLive: true },
  { id: 'int-3', name: 'RT', category: 'international', logo: 'R', gradient: 'from-green-600 to-green-800', isLive: true },
  { id: 'int-4', name: 'NHK World', category: 'international', logo: 'N', gradient: 'from-red-600 to-red-800', isLive: true },
  { id: 'int-5', name: 'CGTN', category: 'international', logo: 'C', gradient: 'from-orange-600 to-orange-800', isLive: true },
  { id: 'int-6', name: 'Euronews', category: 'international', logo: 'E', gradient: 'from-purple-600 to-purple-800', isLive: false },
  { id: 'hd-1', name: 'Sony HD', category: 'hd', logo: 'S', gradient: 'from-indigo-600 to-indigo-800', isLive: true },
  { id: 'hd-2', name: 'Star Sports HD', category: 'hd', logo: 'S', gradient: 'from-yellow-600 to-yellow-800', isLive: true },
  { id: 'hd-3', name: 'Discovery HD', category: 'hd', logo: 'D', gradient: 'from-blue-600 to-blue-800', isLive: true },
  { id: 'hd-4', name: 'National Geo HD', category: 'hd', logo: 'N', gradient: 'from-yellow-500 to-yellow-700', isLive: true },
  { id: 'hd-5', name: 'HBO HD', category: 'hd', logo: 'H', gradient: 'from-purple-700 to-purple-900', isLive: true },
  { id: 'hd-6', name: 'Movies Now HD', category: 'hd', logo: 'M', gradient: 'from-red-600 to-red-800', isLive: false },
  { id: 'live-1', name: 'Premier League Live', category: 'live', logo: 'P', gradient: 'from-purple-700 to-purple-900', isLive: true },
  { id: 'live-2', name: 'Cricket Live 1', category: 'live', logo: 'C', gradient: 'from-green-600 to-green-800', isLive: true },
  { id: 'live-3', name: 'UFC Fight Night', category: 'live', logo: 'U', gradient: 'from-red-700 to-red-900', isLive: true },
  { id: 'live-4', name: 'Formula 1 Live', category: 'live', logo: 'F', gradient: 'from-red-600 to-red-800', isLive: true },
  { id: 'live-5', name: 'NBA Live', category: 'live', logo: 'N', gradient: 'from-blue-600 to-blue-800', isLive: false },
  { id: 'live-6', name: 'Concert Live', category: 'live', logo: 'C', gradient: 'from-pink-600 to-pink-800', isLive: true },
];

export const channels = baseChannels.map((channel) => ({
  ...channel,
  streamUrl: channel.isLive ? DEMO_HLS_URL : DEAD_HLS_URL,
  gradientStyle: gradientMap[channel.gradient] || 'linear-gradient(135deg, #7c3aed 0%, #be185d 100%)',
}));
